### ISSUE TITLE
Duplicate `/july` page.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Ono-College-New-Site#17]
Client wants another page under `/haifa` which should be a duplicate of `/july`. Just functionality should be done, content will be fixed by @hanan-avzuk.

**Comment by VladimirWebDev** [comment]
Just one question. Pages March, July and November used march gallery group for tutors and graduates. On demand, for Haredim page I"ve created specific gallery group for Haredim. Should I create also specific Haifa gallery groups or leave March gallery..?

**Comment by VladimirWebDev** [comment]
Also, is there any change on phone number (contact number), since it's coming from language constant.?

**Comment by MeanEYE** [comment]
For now yes. Both stay the same as other pages.
