### ISSUE TITLE
Add content under 'july_subjects'

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-College-New-Site#2]
Please add the next line of content under july_subjects.

*Hebrew content brakes here. Content will provide via email - Mladen's.

Set font size to 0.8 rem.

![image](https://user-images.githubusercontent.com/26923359/28315429-14be46a2-6bc7-11e7-8823-44c2c1b8d729.png)

**Comment by MeanEYE** [comment]
And again. Content needs to be here. 
I don't want emails, whatsapps, pigeons or whatever else you think is suitable. 
Otherwise I'll just turn to smart ass move and write "Content" on page.

**Comment by hanan-avzuk** [comment]
* הענקת התואר מותנית באישור המל״ג. לתכנית רשת ביטחון מלאה ממסלול ה M.B.A - של הקריה האקדמית אונו 
כל שאר התארים מוכרים על ידי המל"ג.
