### ISSUE TITLE
Duplicate openday july

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-College-New-Site#26]
We need to duplicate July open day page http://openday.ono.ac.il/july

- [x] New URL: http://openday.ono.ac.il/leumi

- [x] Remove phone number from the page

- [x] New logo. Will provide via email

- [x] New header image will be provided via email

- [x] Remove compeny collaborators section (those 5 logos)

- [x] Duplicate all images as well

as for the things I didn't mention, all stay the same.

**Comment by MeanEYE** [comment]
New logo? For the entire site?

**Comment by talovdat** [comment]
New logo should be presented only here: 

![image](https://user-images.githubusercontent.com/26923359/40975692-68c3a8ae-68d4-11e8-8968-3e0658671b15.png)


This logo apply only to /leumi
