### ISSUE TITLE
Adding text on leumi page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-College-New-Site#28]
![image](https://user-images.githubusercontent.com/26923359/41029265-ebe02ba4-6983-11e8-95d1-d560572d80d2.png)

I need to add a word in the area that marked in the screenshot above. 
Is it through the language file?

**Comment by VladimirWebDev** [comment]
@talovdat  It's in language file, constant `graduates`.

**Comment by MeanEYE** [comment]
This also means it will change on other pages.

**Comment by talovdat** [comment]
Okay, so no need.
Am closing issue.

**Comment by talovdat** [comment]
Reopening the issue.
@MeanEYE , should I add the text in language file?

**Comment by MeanEYE** [comment]
@talovdat no. @VladimirWebDev will do that. Further more only this page needs to use this constant.

**Comment by talovdat** [comment]
So the text goes next to the text they already have 
![image](https://user-images.githubusercontent.com/26923359/41046003-38e40398-69b2-11e8-84b2-c6774abcdb1c.png)


The words we need to add is ותלמידנו
