### ISSUE TITLE
Make asterisk content smaller

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-College-New-Site#3]
Please make the asterisk content smaller.
![image](https://user-images.githubusercontent.com/26923359/28569154-58990dec-7141-11e7-92ce-fde1a7066dbb.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev There's a section article in LESS files. This text is inside of `small` tag, so all that's needed to be done is to create new selector for `<small>` inside of that article and set font to something like `0.7em`.

**Comment by MeanEYE** [comment]
@VladimirWebDev There's a section article in LESS files. This text is inside of `small` tag, so all that's needed to be done is to create new selector for `<small>` inside of that article and set font to something like `0.7em`.
