### ISSUE TITLE
Align articles on `July` so that space indicated on screen shot is not present.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-College-New-Site#4]
Please make July articles show in a symmetrical way.

![image](https://user-images.githubusercontent.com/26923359/32991443-70f25a42-cd44-11e7-9539-545051075cf3.png)

**Comment by MeanEYE** [comment]
Explain your understanding of symmetrical.

**Comment by talovdat** [comment]
Those two small articles windows should be parallel to the right in relation to the larger article window shown on the left.

**Comment by MeanEYE** [comment]
That is not what symmetrical means. But okay.

**Comment by MeanEYE** [comment]
@VladimirWebDev double-check that this is not a browser issue. I don't remember this being present when we first uploaded the site.
