### ISSUE TITLE
Remove specific text from site

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-College-New-Site#5]
Please remove the next text from the page: 
![image](https://user-images.githubusercontent.com/26923359/33021591-1514a320-ce0b-11e7-8902-9b9ffebf9fc2.png)

**Comment by MeanEYE** [comment]
This is only on `/july` page. Tal already removed language constant. Code that uses it need to be removed as well. Make sure that constant is not used on other pages. If it is, rollback change @talovdat made.
