### ISSUE TITLE
Add a new article

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-College-New-Site#8]
Please add a new article next to the top container. 

![image](https://user-images.githubusercontent.com/26923359/34462827-a8c1210c-ee54-11e7-91e9-4c4b62bc2f7a.png)

**Comment by MeanEYE** [comment]
Why when they asked to remove it some time ago. And what's the content of this article?

**Comment by talovdat** [comment]
Content: "Ono open day! 1.10.2018! Get your discount today" and then a
short list of subjects.

The sale became relevant so the need it up again.
Can we make it a manageable article through the backend office?

On 2 Jan 2018 11:40 am, "Mladen Mijatov" <notifications@github.com> wrote:

Why when they asked to remove it some time ago. And what's the content of
this article?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Way2CU/Ono-College-New-Site/issues/8#issuecomment-354730018>,
or mute the thread
