### ISSUE TITLE
Discount article visability

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Ono-College-New-Site#9]
We need to add the discount article that used to be there. 
The article already exists in the backend office but is not visible.

![image](https://user-images.githubusercontent.com/26923359/36730555-8835ea04-1bd0-11e8-988d-e7d1f4ffdfb9.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev this feature was already there but was removed. It needs to be checked whether CSS code is still there, if not it should be dug up from history. Additionally this article should respect `visible` parameter so they have ability to hide and show and not bother us every time such thing is needed.

**Comment by VladimirWebDev** [comment]
@talovdat  I added visibility option for discount article. If they do not want to display discount they just have to uncheck article - visible. 
![image](https://user-images.githubusercontent.com/25882157/36848202-d7d32568-1d60-11e8-9e77-0cec144dbdc7.png)
Applied to July and November pages.
